%% Mermaid AWS EC2 Data Flow Diagram
%% For more information on mermaid, see https://knsv.github.io/mermaid/

graph LR
  subgraph AWS
    instance[EC2 instance]
    vmhost[VM Host]
    api[API]
    console[Console]
    cloudformation[CloudFormation]

    instance --- vmhost
    api --> instance
    console --> instance
    cloudformation --> instance
    api --> cloudformation
    console --> cloudformation
  end
  
  subgraph External
    user[User]
    service[Service]
  end

  user --> api
  user --> console
  user -.-> instance
  service -.-> instance

